mode: train
epochs: 50
batch_size: 16
seed: 42
augment: default
class_mode: binary # multiclass or binary
out_classes: 1 # 1 for binary, 3 for multiclass


loss:
  name: smpDiceLoss # smpDiceLoss, DiceFocalLoss, DiceBCELoss, DiceWithBoundaryLoss, DiceCrossEntropy

lr:
  base_lr: 0.001

train_strategy: ddp # auto or ddp

cuda_visible_devices: [5,6]

dataset:
  normalize: true
  workers: 16

trainer:
  max_epochs: ${train.epochs}
  enable_progress_bar: true
  log_every_n_steps: 1
  enable_model_summary: true
  num_sanity_val_steps: 0
  deterministic: true  # true for binary, false for multiclass
  
callbacks:
  monitor: valid_dataset_iou
  mode: max
  save_top_k: 1
  save_last: true

sample_inference:
  - "data/rye_vetch/biomass-data/images/NC01_2024_CC_TM-2_TR-102_5_rgb_1c1d663f-5fbb-4959-a26a-dfa369eb9a9c.jpg" # mostly vetch
  - "data/rye_vetch/biomass-data/images/OH_2024_CC_TM-2_TR-001_1_rgb_0ed7bc9f-c90f-4ce1-9ccc-8ffad0f2f3b0.jpg" # balanced
  - "data/rye_vetch/biomass-data/images/PA_2024_CC_TM-1_TR-002_5_rgb_02ec0f25-0318-45ba-a2a9-8c7c5b0635e4.jpg" # mostly grass