mode: train
epochs: 5
batch_size: 16
augment: very_basic

train_strategy: auto # auto or ddp

cuda_visible_devices: [1]

trainer:
  max_epochs: ${train.epochs}
  enable_progress_bar: true
  log_every_n_steps: 1
  enable_model_summary: true
  num_sanity_val_steps: 0
  deterministic: false  # true for binary, false for multiclass
  
callbacks:
  monitor: valid_dataset_iou
  mode: max
  save_top_k: 1
  save_last: true
