mode: preprocess

tasks:
  move_fullsized_data: false
  remove_nontargets: false
  grid_crop: false # successfully tested
  train_val_test_split: true # successfully tested
  remap_masks: true # successfully tested
  data_stats: false # successfully tested
  viz_results: false

data_dir: ${paths.root_dir}/data/SYNTHETIC_HV_CC

move_fullsized_data:
  query_result: data/balanced_dataset.json
  remove_unmatched: True # remove images that do not have masks and vice-versa

remove_nontargets:
  remove_colorchecker: True

grid_crop:
  crop_height: 512
  crop_width: 512

train_val_test_split:
  train_size:  # not used, train_size is calculated from val_size and test_size
  val_size: 0.1
  test_size: 0.1
  seed: 42
  use_concurrency: True
  remove_cropped_data: True
  
  model_testing: # quick and dirty way to generate a small dataset, not recommended for final results
    status: false
    factor: 0.01

remap_masks:
  group_name: vegetation # must be one of "family", "order", "genus", "subclass", "growth_habit", "group", "vegetation"
  process_concurrently: True

data_stats:
  ignore_background: False # True ignores the background class for plotting

viz_results:
  model_dir_n:  # model subdirectory to visualize