tasks:
  find_images: false
  remove_nontargets: false # If true, only moves synthetic masks if use_synthetic is true
  grid_crop: false # successfully tested
  remap_masks: false # successfully tested
  train_val_test_split: true # successfully tested
  
  data_stats: true # successfully tested
  viz_results: false

use_synthetic:
  enable: true
  project_name: hairy_vetch
  sub_project:  # ignored if use_all_subprojects is true
  use_all_subprojects: true

remove_nontargets:
  remove_colorchecker: True

grid_crop:
  crop_height: 2048
  crop_width: 2048

remap_masks:
  group_name: group # must be one of "family", "order", "genus", "subclass", "growth_habit", "group", "vegetation"
  process_concurrently: False

train_val_test_split:
  train_size:  # not used, train_size is calculated from val_size and test_size
  val_size: 0.1
  test_size: 0.1
  seed: 42
  use_concurrency: True
  remove_cropped_data: True
  
  model_testing: # quick and dirty way to generate a small dataset, not recommended for final results
    status: false
    factor: 0.01

data_stats:
  ignore_background: False # True ignores the background class for plotting

viz_results:
  model_dir_n:  # model subdirectory to visualize