tasks:
  find_images: true
  remove_nontargets: true
  grid_crop: true # successfully tested
  remap_masks: true # successfully tested
  train_val_test_split: true # successfully tested
  
  data_stats: true # successfully tested
  viz_results: false

remove_nontargets:
  remove_colorchecker: True

grid_crop:
  crop_height: 1024
  crop_width: 1024

remap_masks:
  group_name: vegetation # must be one of "family", "order", "genus", "subclass", "growth_habit", "group", "vegetation"
  process_concurrently: False

train_val_test_split:
  train_size:  # not used, train_size is calculated from val_size and test_size
  val_size: 0.1
  test_size: 0.1
  seed: 42
  use_concurrency: True
  remove_cropped_data: True
  
  model_testing: # quick and dirty way to generate a small dataset, not recommended for final results
    status: false
    factor: 0.01

data_stats:
  ignore_background: False # True ignores the background class for plotting

viz_results:
  model_dir_n:  # model subdirectory to visualize