defaults:
  - paths: default           # Default paths config
  - preprocess: default          # Default training config

  # Training configs
  - dataset: combined_veg       # Default dataset config
  - augment: basic  # Default augmentations config
  - train: default         # Train config
  - model: deeplabv3plus         # Model config
  - inference: default      # Inference config
  - _self_                   # Ensures overriding behavior

project:
  name: "COMBINED"
  subname: ${dataset.data_name}
  output_dir: ${hydra:runtime.cwd}/lightning_logs/${project.name}

logger:
  save_dir: ${project.output_dir}
  name: ${project.subname}

tasks:
  # - move_fullsized_data
  - grid_crop
  - train_val_test_split
  - remap_masks
  - data_stats
  # - smptrain
  # - inference

job_now_date: &nowdir ${now:%Y-%m-%d}
job_now_time: &nowtime ${now:%H:%M:%S}

mode: ??? # required argument for command line. Either train or inference

hydra:
  run:
    dir: ${project.output_dir}/${project.subname}/${mode}/hyrda/${job_now_date}_${job_now_time}  # Dynamically set the directory based on task
  # output_subdir: "default"