defaults:
  - paths: default           # Default paths config
  # Training configs
  - dataset: combined_veg       # Default dataset config
  - augment: basic  # Default augmentations config
  - train: default         # Train config
  - model: deeplabv3plus         # Model config
  - inference: default      # Inference config
  - preprocess: default          # Default training config
  - _self_                   # Ensures overriding behavior

project:
  name: "SEMIF"
  subname: ${dataset.data_name}
  output_dir: ${hydra:runtime.cwd}/projects/${project.name}/${mode}

logger:
  save_dir: ${project.output_dir}
  name: ${project.subname}

job_now_date: &nowdir ${now:%Y-%m-%d}
job_now_time: &nowtime ${now:%H:%M:%S}

mode: ??? # required argument for command line. Either preprocess, train, or inference

hydra:
  run:
    dir: ${project.output_dir}/hydra/${job_now_date}_${job_now_time}  # Dynamically set the directory based on task
  # output_subdir: "default"