train:
  img_hw: ["${preprocess.grid_crop.crop_height}", "${preprocess.grid_crop.crop_width}"]
  
  horizontal_flip: 
    enable: true
    p: 0.1  # Low probability

  vertical_flip: 
    enable: false
    p: 0.0

  affine: 
    enable: false
    scale: 0.0
    translate_percent: 0.0
    translate_px: 
    rotate: [0, 0]
    shear: 0
    interpolation: 0 
    mask_interpolation: 0 
    fit_output: True
    keep_ratio: True
    rotate_method: largest_box
    balanced_scale: True
    border_mode: 0
    fill: 0.0
    fill_mask: 0.0
    p: 0.0

  optical_distortion: 
    enable: false
    distort_limit: [0.0, 0.0]
    p: 0.0

  padding: 
    enable: false
    p: 0.0

  random_crop: 
    enable: false
    p: 0.0

  gauss_noise: 
    enable: false
    noise_scale_factor: 0.0
    p: 0.0 

  perspective: 
    enable: false
    scale: [0.0, 0.0]
    p: 0.0

  color_transforms:
    enable: true
    transforms:
      - RandomGamma  # Light, deterministic effect
    p: 0.05  # Very low

  blur_transforms:
    enable: false
    transforms: []
    blur_limit: 0
    p: 0.0

  hue_saturation:
    enable: true
    transforms:
      - RandomBrightnessContrast
    brightness_limit: [-0.1, 0.1]
    contrast_limit: [-0.1, 0.1]  
    hue_shift_limit: [0, 0]
    sat_shift_limit: [0, 0]
    val_shift_limit: [0, 0]
    p: 0.05

  noise_transforms:
    enable: false
    one_of_p: 0.0
    transforms: {}

val:
  img_hw: ${augment.train.img_hw}
  padding:
    enable: false
    p: 0.0
