# path to root directory
# this relys on main.py to be run from the project root
root_dir: ${hydra:runtime.cwd}

# path to data directory
data_dir: ${paths.root_dir}/data


# NCSU Storage lockers
primary_storage: /mnt/research-projects/s/screberg/longterm_images
secondary_storage: /mnt/research-projects/s/screberg/GROW_DATA

preprocess:
  # path to original data
  image_dir: ${preprocess.data_dir}/images
  mask_dir: ${preprocess.data_dir}/masks

  # path to cropped data
  crop_suffix: ${preprocess.grid_crop.crop_height}x${preprocess.grid_crop.crop_width}
  cropped_image_dir: ${project.output_dir}/data/cropped_images_${paths.preprocess.crop_suffix}
  cropped_mask_dir: ${project.output_dir}/data/cropped_masks_${paths.preprocess.crop_suffix}

  # path to split data
  split_data:
    split_dir: ${project.output_dir}/data/train_val_test_${paths.preprocess.crop_suffix}
    
    datasets:
      - train
      - val
      - test

    dataset_subdirs:
      - images
      - masks
      - remapped_masks
  
train:
  split_data:
    split_dir: ${hydra:runtime.cwd}/projects/${project.name}/preprocess/data/train_val_test_${paths.preprocess.crop_suffix}
    
# model output directory
model_dir: ${paths.root_dir}/models/${project.name}_${paths.preprocess.crop_suffix}/${model.arch}_${model.encoder}