# path to root directory
# this relys on main.py to be run from the project root
root_dir: ${hydra:runtime.cwd}

project_dir: ${paths.root_dir}/projects/${project.name}
project_mode_dir: ${paths.project_dir}/${mode}
project_query_dir: ${paths.project_dir}/query
project_preprocess_dir: ${paths.project_dir}/preprocess
project_train_dir: ${paths.project_dir}/train
project_inference_dir: ${paths.project_dir}/inference

# path to data directory
data_dir: ${paths.root_dir}/data


# NCSU Storage lockers
primary_storage: /mnt/research-projects/s/screberg/longterm_images
secondary_storage: /mnt/research-projects/s/screberg/GROW_DATA
tertiary_storage: /mnt/research-projects/s/screberg/longterm_images2

inference_output_dir: ${paths.project_inference_dir}/${inference.inference_subname}/version_${inference.version}/${job_now_date}_${job_now_time}

# path to cropped data
crop_suffix: ${preprocess.grid_crop.crop_height}x${preprocess.grid_crop.crop_width}
cropped_image_dir: ${paths.project_preprocess_dir}/data/cropped_images_${paths.crop_suffix}
cropped_mask_dir: ${paths.project_preprocess_dir}/data/cropped_masks_${paths.crop_suffix}

# path to split data
split_dir: ${paths.project_preprocess_dir}/data/train_val_test_${paths.crop_suffix}

datasets:
  - train
  - val
  - test

dataset_subdirs:
  - images
  - masks

inference:
  checkpoints: ${paths.project_train_dir}/version_${inference.version}/checkpoints


# DB
db:
  # path to db directory
  db_dir: ${paths.data_dir}/db

  # path to db file
  db_file: ${paths.db.db_dir}/agir.db
  lts_db_file: ${paths.tertiary_storage}/semifield-database/agir.db

# Semifield-utils local path
semif_utils_dir: ${paths.data_dir}/semifield-utils

# Species information
species_info_dir: ${paths.semif_utils_dir}/species_information
species_info_file: ${paths.species_info_dir}/species_info.json
lts_species_info: ${paths.tertiary_storage}/semifield-utils/species_information/species_info.json