import os
import pandas as pd
import requests
from datetime import datetime

def extract_metrics(csv_path):
    if not os.path.exists(csv_path):
        print(f"Metrics file not found: {csv_path}")
        return "N/A", "N/A", ""

    df = pd.read_csv(csv_path)
    if df.empty:
        return "N/A", "N/A", ""

    latest = df.iloc[-1]
    dataset_iou = latest.get("valid_dataset_iou", "N/A")
    per_image_iou = latest.get("valid_per_image_iou", "N/A")

    # Keep only useful columns for the table
    columns_to_include = [
        "epoch", "step", "train_loss", "valid_loss", 
        "valid_dataset_iou", "valid_per_image_iou"
    ]
    df_trimmed = df[columns_to_include].tail(5).fillna("-")  # last 5 rows only
    markdown_table = df_trimmed.to_markdown(index=False)

    return dataset_iou, per_image_iou, markdown_table

def create_issue(repo, token, title, body):
    url = f"https://api.github.com/repos/{repo}/issues"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json"
    }
    payload = {
        "title": title,
        "body": body,
        "labels": ["training"]
    }
    response = requests.post(url, headers=headers, json=payload)
    if response.status_code == 201:
        print("✅ Issue created successfully!")
    else:
        print("❌ Failed to create issue:", response.status_code)
        print(response.text)
        exit(1)

def main():
    repo = os.environ.get("GITHUB_REPOSITORY")
    token = os.environ.get("GH_TOKEN")
    project_name = os.environ.get("PROJECT_NAME", "unknown_project")
    csv_path = f"projects/{project_name}/train/version_0/metrics.csv"

    dataset_iou, per_image_iou, markdown_table = extract_metrics(csv_path)

    title = f"Training Report - {project_name} - {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    body = f"""
### 🧠 Segmentation Model Training Report

**Project:** `{project_name}`  
**Run Time:** {datetime.now().isoformat()}

**Validation Dataset IoU:** `{dataset_iou}`  
**Validation Per-Image IoU:** `{per_image_iou}`
**Training Metrics:**

### 📊 Last 5 Training Steps

```markdown
{markdown_table}
```
**Note:** This issue is auto-generated by the training script. Please do not edit it manually.
**For more details, check the training logs.**

"""
    create_issue(repo, token, title, body)


if __name__ == "__main__":
    main()