mode: inference

subname: CCCamImages
input_dir: "data/CCCamImages/images"
# input_dir: "data/COMBINED_VEG_TEST/train_val_test_256x256/test/images"

version: 4

rescale_factor: .75
threshold: 0.75
use_normalization: true

cuda_visible_devices: [5]

samplek: 10

seed: 42

mean: 
  - 0.41359323636007883
  - 0.3630233380560909
  - 0.3157344799924196
std:
  - 0.1193212211964802
  - 0.11448691093594061
  - 0.09600069526132719

inference_root: ${project.output_dir}/${inference.subname}/version_${inference.version}
inf_scaled_thresh: scaled_${inference.rescale_factor}_thresh_${inference.threshold}_norm_${inference.use_normalization}

inf_output_dir: ${inference.inference_root}/${inference.inf_scaled_thresh}

plot:
  dpi: 300
  transparent: true

CCCamImages:
  mean: 
    - 0.41359323636007883
    - 0.3630233380560909
    - 0.3157344799924196
  std:
    - 0.1193212211964802
    - 0.11448691093594061
    - 0.09600069526132719