title: SemiF-Segmentation Tutorial
remote_theme: just-the-docs/just-the-docs

# Navigation
nav_sort: case_sensitive

# Aux links (shown in upper right)
aux_links:
  "View on GitHub":
    - "https://github.com/precision-sustainable-ag/SemiF-Segmentation"

color_scheme: dark

aux_links:
  "View on GitHub":
    - "https://github.com/precision-sustainable-ag/SemiF-Segmentation"

mermaid:
  version: "11.6.0"  # Pick the version you want
  # Default configuration
  config: |
    directionLR

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
  best-practice:
    title: Best Practice
    color: green

# The custom navigation
nav:
  - Home: index.md       # Link to your main docs index
  - GitHub: "https://github.com/precision-sustainable-ag/SemiF-Segmentation"